---
# Tasks for local_dns role
# Manages /etc/hosts (Linux/macOS) or C:\Windows\System32\drivers\etc\hosts (Windows)
# from network_registry.yml

- name: Load network registry
  ansible.builtin.include_vars:
    file: "{{ network_registry_path }}"
    name: registry

- name: Set dns_records fact
  ansible.builtin.set_fact:
    dns_records: "{{ registry.dns_records }}"

# Include OS-specific tasks
- name: Include Linux/macOS tasks
  ansible.builtin.include_tasks: linux.yml
  when: ansible_os_family != "Windows"

- name: Include Windows tasks
  ansible.builtin.include_tasks: windows.yml
  when: ansible_os_family == "Windows"
